services:
  app:
    build:
      context: .
      target: web
    image: rs3-quest-buddy:web_beta
    container_name: rs3questbuddy_beta_app
    restart: unless-stopped
    environment:
      PORT: "8080"
      NODE_ENV: "production"
    depends_on:
      rs3questbuddy-db:
        condition: service_healthy
    networks:
      - app_net